image: quay.io/glennhickey/cactus-ci-base:latest

before_script:
  - whoami
  - sudo apt-get -q -y update
  - sudo apt-get -q -y install redis-server libhiredis0.13 libhiredis-dev
  - startdocker || true
  - docker info

after_script:
  - stopdocker || true
  
stages:
  - test

test-job:
  stage: test
  script:
    - git submodule update --init --recursive
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - pip install -r toil-requirement.txt
    - pip install -U .
    - build-tools/downloadMiniTools
    - make -j 8 evolver_test
  artifacts:
    # Let Gitlab see the junit report
    #reports:
    #  junit: test-report.xml
    #when: always
  
