sudo: required
dist: trusty
language: c++
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libtokyocabinet-dev libkyototycoon-dev kyototycoon libkyotocabinet-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tokyo-cabinet kyoto-cabinet kyoto-tycoon; fi
#Build docker containers
  - if [[ "$CACTUS_DOCKER_MODE" == 1 ]]; then docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io; make push; fi
script:
  - sudo pip install --pre toil
  - sudo pip install -e .
  - if [[ "$CACTUS_DOCKER_MODE" == 0 ]]; then make && PATH=`pwd`/bin PYTHONPATH=`pwd`:`pwd`/src make test; fi
  - if [[ "$CACTUS_DOCKER_MODE" == 1 ]]; then make test; fi
os:
  - linux
services:
  - docker
env:
  - CGL_DEBUG=1 CACTUS_DOCKER_MODE=0
  - CACTUS_DOCKER_MODE=1
  - CGL_DEBUG=ultra ASAN_OPTIONS=detect_leaks=0 CACTUS_DOCKER_MODE=0
