sudo: required
dist: trusty
language: c++
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libtokyocabinet-dev libkyototycoon-dev kyototycoon libkyotocabinet-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tokyo-cabinet kyoto-cabinet kyoto-tycoon; fi
  - git clone https://github.com/ComparativeGenomicsToolkit/sonLib.git
  - git clone https://github.com/ComparativeGenomicsToolkit/matchingAndOrdering.git
  - git clone https://github.com/ComparativeGenomicsToolkit/pinchesAndCacti.git
  - git clone https://github.com/benedictpaten/jobTree.git
  - git clone https://github.com/benedictpaten/cPecan.git
#Build docker containers
  - if [[ "$BUILD_CONTAINERS" == 1 ]]; then docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io; git submodule update --init; make docker; make push; fi
install:
  - export sonLibRootPath=`pwd`/sonLib
  - sh -c 'cd sonLib && make'
  - sh -c 'cd matchingAndOrdering && make'
  - sh -c 'cd pinchesAndCacti && make'
  - sh -c 'cd cPecan && make'
script:
  - export sonLibRootPath=`pwd`/sonLib
  - make
  - pip install --pre toil
  - pip install -e .
  - if [[ "$BUILD_CONTAINERS" == 1 ]] ; then PATH=./bin:./sonLib/bin:$PATH PYTHONPATH=.:src make test; fi
os:
  - linux
services:
  - docker
env:
  - BUILD_CONTAINERS=1
#  - CGL_DEBUG=1 BUILD_CONTAINERS=0
#  - CGL_DEBUG=ultra ASAN_OPTIONS=detect_leaks=0 BUILD_CONTAINERS=0
