sudo: required
dist: trusty
language: c++
before_install:
  - git clone https://github.com/benedictpaten/sonLib.git
  - git clone https://github.com/benedictpaten/matchingAndOrdering.git
  - git clone https://github.com/benedictpaten/pinchesAndCacti.git
  - git clone https://github.com/benedictpaten/jobTree.git
install:
  - export sonLibRootPath=`pwd`/sonLib
  - sh -c 'cd sonLib && make'
  - sh -c 'cd matchingAndOrdering && git checkout development && make'
  - sh -c 'cd pinchesAndCacti && make'
  - sh -c 'cd jobTree && make'
script:
  - export sonLibRootPath=`pwd`/sonLib
  - make
  - PATH=./bin:./jobTree/bin:$PATH PYTHONPATH=.:.. make test
os:
  - linux
  - osx
env:
  - CGL_DEBUG=1
  - CGL_DEBUG=ultra ASAN_OPTIONS=detect_leaks=0
matrix:
  exclude:
    # The default OSX env doesn't have a version that supports
    # -fsanitize=address.
    - env: CGL_DEBUG=ultra ASAN_OPTIONS=detect_leaks=0
      os: osx
